### ISSUE TITLE
Why is 5.1 re-targeting >7.x Microsoft.Extensions versions (this is a breaking change) 

### ISSUE THREAD

**Issue by Shazwazza** [shawnwildermuth/MetaWeblog#17]
From version 5.0 to 5.1 there is a breaking change in the package since it changes all of the minimum required packages: 

![image](https://user-images.githubusercontent.com/1742685/229571481-3ca1b0d7-1290-4fb5-bdeb-5bd92327f217.png)

To:

![image](https://user-images.githubusercontent.com/1742685/229571553-b3430f04-83f6-4885-ad71-a55ed1342145.png)

There doesn't seem to be a requirement for those minimum version since I don't think there are specific new APIs being used? Is it possible to revert to have the previous minimum version requirements?

**Comment by shawnwildermuth** [comment]
Let me check out why. I don't remember making a change like that.

**Comment by shawnwildermuth** [comment]
I rolled back those updates, not sure why they were done.  I have updated the nuget package to 5.1.1 with this fix.

**Comment by Shazwazza** [comment]
Fantastic, thanks @shawnwildermuth 😁
