### ISSUE TITLE
Error in Open Live Writer

### ISSUE THREAD

**Issue by nj00** [shawnwildermuth/MetaWeblog#2]
Hello, Shawn. 

Because I am not good at English, this sentence uses automatic translation.
I'm sorry if it's difficult to read.

Currently I am creating my own blog site with ASP.NET Core 1.1.
I'm considering introducing **WilderMinds.MetaWeblog** to allow you to post articles using **Open Live Writer** like **WilderBlog**. But the first Wizard of **Open Live Writer** encountered an error, and looked at the source of  **MetaWeblog** and **Open Live Writer**.

The **Invoke** method of the source **"MetaWeblogMiddleware.cs"** _context.Response.WriteAsync_. The later **return;** is not necessary or not?

```c#
        public async Task Invoke(HttpContext context)
        {
            if (context.Request.Method == "POST" &&
              context.Request.Path.StartsWithSegments(_urlEndpoint) &&
              context.Request != null &&
              context.Request.ContentType.ToLower().Contains("text/xml"))
            {
                var rdr = new StreamReader(context.Request.Body);
                var xml = rdr.ReadToEnd();
                _logger.LogInformation($"Request XMLRPC: {xml}");
                var result = _service.Invoke(xml);
                _logger.LogInformation($"Result XMLRPC: {result}");
                context.Response.ContentType = "text/xml";
                await context.Response.WriteAsync(result, Encoding.UTF8);
                
                return;  // <- this line is not necessary?
            }

            // Continue On
            await _next.Invoke(context);
        }
```

In **Configure** method of the Web site's **Startup** class,  there is a **app.UseMvc()** after **app.UseMetaWeblog()**.

It seems to be an error because the content of the response has been replaced by MVC after the call to MetaWeblogAPI. I was able to understand the phenomenon, but as a **WilderMinds.MetaWeblog design**, is the **return** sentence here a good one?

For now, I will report.

**Comment by shawnwildermuth** [comment]
Let check and look at this

**Comment by shawnwildermuth** [comment]
The return is required as we don't want to call the rest of the middleware if we've completed the request.
