### ISSUE TITLE
AppVeyor Builds Failing

### ISSUE THREAD

**Issue by jasongaylord** [shawnwildermuth/MetaWeblog#4]
It appears that AppVeyor is having a tough time getting the PowerShell scripts to download .NET Core from https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1. It's receiving a 404 which makes sense since it's no longer there. I'm not sure what project the install scripts were moved to.

**Comment by shawnwildermuth** [comment]
I'll fix it soon, I need to finish the course I'm working on then I'll get back to these. The old scripts here are ancient. Much easier now. Need to just start the appveyor scripts from scratch.

**Comment by shawnwildermuth** [comment]
This is solved in latest build moving to .NET Standard 2.0

**Comment by jasongaylord** [comment]
Thanks @shawnwildermuth! Why did you have to switch it to netstandard as opposed to netcore?

**Comment by shawnwildermuth** [comment]
So that people running .net 4.* can use it too

**Comment by jasongaylord** [comment]
Got it. Just curious. Thanks Shawn!
